### ISSUE TITLE
Add flags for setting config fields

### ISSUE THREAD

**Issue by TaKO8Ki** [TaKO8Ki/frum#39]
I want to add the following options corresponding to `Config` struct fields.

https://github.com/TaKO8Ki/frum/blob/88d29262ee0b538fdd4b570eac4d938e6d9caa98/src/config.rs#L5-L10

|  field name  |  option name  | description |
| ---- | ---- | ---- |
|  `base_dir`  |  `--farm-dir`  | - |
|  `ruby_build_mirror`  |  `--ruby-build-mirror`  | - |
|  `log_level`  |  `--log-level`  | error or info or quiet. default: info |

- [ ] `--frum-dir`
- [ ] `--ruby-build-mirror`
- [x] `--log-level`

**Comment by citizen428** [comment]
Could you elaborate a bit, which config fields, etc?

**Comment by TaKO8Ki** [comment]
@citizen428 
I added some descriptions!
