### ISSUE TITLE
[FEATURE REQUEST] frum --quiet or -q

### ISSUE THREAD

**Issue by gregf** [TaKO8Ki/frum#41]
I love it so far, just needs a quiet option. I'm not a fan of seeing the error message about not finding a ruby-version file every time I cd to a  directory.

Just a FYI, I'm on FreeBSD 13, and it's working great. Thank you for your work.

**Comment by TaKO8Ki** [comment]
Thank you for your feedback! I agree with that. I'm going to fix that.

**Comment by TaKO8Ki** [comment]
I opend an issue about that. https://github.com/TaKO8Ki/frum/issues/42
