### ISSUE TITLE
Turn off error messages after running `cd ` command

### ISSUE THREAD

**Issue by TaKO8Ki** [TaKO8Ki/frum#42]
ref https://github.com/TaKO8Ki/frum/issues/41#issue-865983061

**Comment by citizen428** [comment]
Just to clarify, should this be the default behavior or behind a `-q` switch (IMO default). Also, would you accept a contribution for this?

**Comment by TaKO8Ki** [comment]
@citizen428 Sure! I think it is good to add --quiet flag to local command and use this flag in use_on_cd functions for each shell.
