### ISSUE TITLE
Add `--with-jemalloc` option

### ISSUE THREAD

**Issue by jonian** [TaKO8Ki/frum#50]
Hi @TaKO8Ki, it would be nice if frum had an option to build with jemalloc, since it is a common optimization flag. Alternatively frum could allow to pass any options when building ruby using the syntax below (used in [ruby-install](https://github.com/postmodern/ruby-install)):

```sh
frum install 3.0.1 -- --with-jemalloc
```

**Comment by citizen428** [comment]
I'd like to work on this @TaKO8Ki (I actually already started 😅 ).

**Comment by TaKO8Ki** [comment]
@citizen428 
Sure! Please feel free to ask questions :)
