### ISSUE TITLE
Aliases don't seem to work

### ISSUE THREAD

**Issue by carlo** [TaKO8Ki/frum#87]
## Issue description

I've symlinked Ruby minor versions in `$FRUM_DIR/aliases/`, e.g. `3.0 → 3.0.2`.  Unfortunately, when using the aliases in a  `.ruby-version` file, they don't seem to do anything, and frum reverts to the global version.

My `FRUM_DIR` is set to `~/.cache/frum/`.

## Steps to reproduce the issue

1. Create new folder, inside create a `.ruby-version` version file containing an alias version.
2. Change out of the folder, then back in to that folder.

## What's the expected result?

When changing into `alias-test/`, frum resolves the alias `2.7` found in the `.ruby-version` file to `2.7.4` and sets Ruby 2.7.4.

## What's the actual result?

When changing into `alias-test/`, frum doesn't resolve the alias `2.7` and instead falls back to my globally set Ruby 3.0.2.

Screenshot:

<img width="897" alt="cleanshot-2021-07-21-124442@2x" src="https://user-images.githubusercontent.com/1501/126476556-c81ecd11-b53e-4831-9ac5-06a657cd8da9.png">

Note the Ruby version in the last prompt.

**Comment by TaKO8Ki** [comment]
@carlo 
Thank you for opening the issue! I'll investigate the cause of the bug 👍

**Comment by TaKO8Ki** [comment]
@carlo 
I'm sorry for the late reply. I created frum referencing to rbenv, so frum does not support version aliases like rvm.

**Comment by carlo** [comment]
Oh, alright.  Well, not a problem, thanks for getting back to me!
