### ISSUE TITLE
Fix use of temporary path to managed binaries

### ISSUE THREAD

**Issue by bkuhlmann** [TaKO8Ki/frum#88]
## Overview

When using `command -v`, I noticed Frum is pointing to temporary paths for all Ruby related binaries. I assume this is a bug?

## Steps to Recreate

``` bash
brew install frum

export FRUM_DIR="$HOME/.cache/frum"
eval "$(frum init)"

frum install 3.0.2
frum global 3.0.2
gem install pennyworth

# Notice the following paths all use temporary directories instead of the Frum cache as defined above.
command -v ruby        # => /var/folders/j1/szrwbp9d1jg351ghw4f7bcym0000gn/T/frum_1956_1627218393720/bin/ruby
command -v pennyworth  # => /var/folders/j1/szrwbp9d1jg351ghw4f7bcym0000gn/T/frum_1956_1627218393720/bin/pennyworth
```

## Desired Behavior

I would expect to see the full path to where the Frum cache is located. So something more along these lines, for example:

``` bash
$HOME/.cache/frum/versions/3.0.2/lib/ruby/gems/3.0.0/gems/pennyworth-11.1.1/bin
```

## Environment

- **Operating System**: macOS 11.5 (20G71)
- **Frum**: 0.1.0

**Comment by TaKO8Ki** [comment]
Thank you for opening the issue. It is not a bug. frum uses temp dir to switch ruby versions in the following functions.

https://github.com/TaKO8Ki/frum/blob/b5b7a8acb676da410120adcbc12988b3b6a89db8/src/commands/init.rs#L51-L61

**Comment by TaKO8Ki** [comment]
@bkuhlmann 
Do you have any reason why you want to see the full path?

**Comment by bkuhlmann** [comment]
Hey Takayuki, yep, it's because of a several of reasons:

- Necessary to debug ruby and/or gem dependency issues. It's much easier to use `command -v` to discover which directory I need to jump into to open up source code and even manipulate directly.
- I haven't tested this yet, but I think this breaks use of `gem pristine`? So if I edit source, but want Ruby Gems to revert the manipulated gem back to it's pristine/original state will that work?
- For documentation purposes, it's extremely handy to write documentation which points to real directory information with specific version information. For example, this weekend, I was having a discussion related to a macOS specific application and I was trying to show which versions of Ruby I was using but couldn't use `command -v` to obtain that information quickly because I needed the exact path to the binary. 😅 
- Use of `command -v` or `which` should always report the exact path. Current Frum behavior actually breaks that contract we have all come to be used on on Linux systems.
- Using the exact path makes using tools like `fzf`, `bundler`, etc. much easier to dynamically find source locations or compute version comparisons, etc.
- Current Frum behavior deviates from any of the existing Ruby Version Mangers: RVM, rbenv, chruby.

I hope that helps? There is a lot of power in seeing the exact paths. It also helps keep my mind sane when trying to understand the different between the temporary folders and what's in Frum cache. Not having a one-ot-one correlation is definitely hard to reason about or even explain to fellow engineers who are not familiar with Frum.

**Comment by TaKO8Ki** [comment]
@bkuhlmann 

The temp dir frum uses is just a symlink to a specific ruby version directory. So you can see the full path of your Ruby binary like the following workaround. `$FRUM_MULTISHELL_PATH` is an environment variable and the path to the Ruby version directory you use. [fnm](https://github.com/Schniz/fnm), Node.js version manager written in Rust, also uses temp dir to switch Node.js versions and I created frum referencing fnm.

```
$ echo "$(readlink $FRUM_MULTISHELL_PATH)/bin/ruby"
```

> It also helps keep my mind sane when trying to understand the different between the temporary folders and what's in Frum cache.

As mentioned above, the temp dir is just a symlink. So there is no difference between them.

Do you think it would be useful to improve frum so that frum can show the fully resolved binary path of the current Ruby version like the following?

```
$ frum path
=> /Users/foo/.frum/aliases/default/bin/ruby
```

**Comment by bkuhlmann** [comment]
> **Takayuki**: the temp dir is just a symlink. So there is no difference between them.

Thanks! I will use `"$(readlink $FRUM_MULTISHELL_PATH)/bin/ruby"` going forward as that will make documentation much easier for me.

> Do you think it would be useful to improve frum so that frum can show the fully resolved binary path of the current Ruby version like the following?

Yeah, I think it would be most welcome. Mainly because it won't be surprising for people using standard inspection tools like `command` or `which`. Plus, this would match parity with other Ruby Version Managers too and help encourage adoption. :tada:

**Comment by TaKO8Ki** [comment]
That's good to hear. Thank you for your opinion!
