### ISSUE TITLE
gem error: "OpenSSL is not available." on macOS Big Sur

### ISSUE THREAD

**Issue by wfendler** [TaKO8Ki/frum#94]
Using macOS Big Sur 11.5.2 (2019 MBP) I installed frum via homebrew, ran `frum install 3.0.2`, and tried installing a ruby gem (colorls) and received an error about OpenSSL not being available.

```
$ gem install colorls
ERROR:  While executing gem ... (Gem::Exception)
    OpenSSL is not available. Install OpenSSL and rebuild Ruby (preferred) or use non-HTTPS sources
```

I see that you can specify the OpenSSL directory but I'm not sure exactly how this should be used. If Big Sur has OpenSSL at `/usr/bin/openssl` should I be using that? Installing 3.0.2 with `--with-openssl-dir=/usr/bin/openssl` didn't work. I'm not sure what might be going wrong here.

The gem error says to install OpenSSL and rebuild Ruby. I'm able to install OpenSSL (`brew install openssl`) but I'm not sure how to rebuild ruby with frum. 

Is something wrong here or is am I just missing some foundational Ruby knowledge here that is preventing me from getting this to work?

**Comment by TaKO8Ki** [comment]
@wfendler 

Thank you for opening the issue! By default, frum uses OpenSSL installed via Homebrew.  I tried installing Ruby with frum just now in case I've already installed OpenSSL with Homebrew. After that I was able to run `gem install colorls` successfully. If you want to solve your problem quickly, I think you should uninstall Ruby version 3.0.2 and reinstall it when you've already installed OpenSSL with Homebrew like the following.

```
$ brew install openssl
$ frum uninstall 3.0.2
$ frum install 3.0.2
```
 
# Environment
macOS: macOS Bug Sur 11.5.1
OpenSSL: 1.1
Frum: 0.1.1
Ruby: 3.0.2

**Comment by wfendler** [comment]
@TaKO8Ki - Thanks, that was it! I could've sworn I tried it in that order at some point but I must've tried all combinations _except_ that.
